"""first_migration

Revision ID: c49959df784f
Revises: 2dec0ed289a5
Create Date: 2023-02-06 21:28:05.724335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49959df784f'
down_revision = '2dec0ed289a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('qer', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation', 'qer')
    # ### end Alembic commands ###
